// FINISH THE EXAMPLES OF THE ADAPTER CLASS AND USE THE ANONYMOUS EXAMPLE
// AND ADD KEY EVENTS TO IT TO HANDLE JUST THE KEY DOWN EVENT.
// FINISH THE MOUSEMOTIONEVENT DRAGGING THE MOUSE AND USE THE ADAPTER FOR THAT.
// WRAP IT ALL UP IN THE APPLET CLASS AND USE THE SHOWSTATUS() METHOD ALSO WRITE IT TO 
// THE DOS WINDOW.
